
services:
  # MariaDB er her fortsatt, men appen vil ikke bruke den når USE_DYNAMO=true
  db:
    image: mariadb:11
    container_name: videos-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: ${DB_NAME:-videosdb}
      MARIADB_USER: ${DB_USER:-user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-pass}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-project-app
    restart: unless-stopped
    # ikke nødvendig å vente på db, siden DynamoDB brukes
    env_file:
      - .env
    environment:
      CARCOUNTER_SECRET_NAME: "/n12541249/secrets"
      PORT: ${PORT:-3000}
      USE_DYNAMO: "true"
      QUT_USERNAME: "n12541249@qut.edu.au"
      MEMCACHED_ENDPOINT: "carcounting.km2jzi.cfg.apse2.cache.amazonaws.com:11211"
    ports:
      - "3000:3000"   # bytt til "80:3000" hvis du vil bruke port 80 eksternt
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - yolo_cache:/root/.cache/ultralytics
    shm_size: "512m"

volumes:
  db_data:
  yolo_cache:
